### PR TITLE
Support multiple workers

### PR DESCRIPTION
**Pull request by okkez**

### CODE REVIEW

**Review by cosmo0920 — APPROVED** [review]
Oh, I didn't notice about lacking of `multi_workers_ready?` override. LGTM. :+1:

**Comment by okkez** [comment]
@cosmo0920 Could you release new version?

**Comment by cosmo0920** [comment]
Released as v0.2.1: https://rubygems.org/gems/fluent-plugin-map/versions/0.2.1 :tada:

**Comment by okkez** [comment]
Thanks!

**Pull request merged**
