### PR TITLE
Migrate to v0.14 API

### PR DESCRIPTION
**Pull request by cosmo0920**
I've migrated this plugin to use v0.14 API and leave gem version as-is.
Please release new version which specifies fluentd v0.12 as upper bound before merging this.

### CODE REVIEW

**Comment by tomity** [comment]
Thank you for sending Pull Request. 
Because current stable version of fluentd is 0.12.29, it is too early to remove v0.12 dependency.
Please correct the dependency for fluentd.

**Comment by cosmo0920** [comment]
> Because current stable version of fluentd is 0.12.29, it is too early to remove v0.12 dependency.
> Please correct the dependency for fluentd.

Sadly, this migrated plugin does NOT work with current stable version (0.12.x) of Fluentd.
v0.14 API can work with Fluentd 0.14.x or later.
It is ok for me to leave this PR as-is until v0.14 will get stable or be released v1.

**Comment by cosmo0920** [comment]
memo: We should migrate filter version of map plugin instead of output one.
This PR should leave as-is until creating PR which migrates filter version of this plugin. 
Output version should be deprecated and show warnings in the future.

**Comment by cosmo0920** [comment]
Closing in favor of https://github.com/fluent-plugins-nursery/fluent-plugin-map/pull/18.

**Pull request closed without merging**
